### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by marcelvanherk** [Quantx/dgnsdk#2]
Hi,

I wrote my 'assembler' in lua (a works in progress). It would be great if you can add an example program to your assembler. Love to give it a try on my Nova 1210.

Marcel

**Comment by marcelvanherk** [comment]
And sorry, the project has two dependencies I do not have on my windows system, a.out.h and novanix.h. Can you include those?

Thanks

**Comment by Quantx** [comment]
Sorry, I added the missing files you'll need.

I've been busy, greatly expanding the scope of this project and just now updated the github.

**Comment by Quantx** [comment]
I'm in the process of fleshing out the Wiki, so be sure to check there for more info
